### ISSUE TITLE
现在好像发布作品不了了，你那还可以吗？

### ISSUE THREAD

**Issue by chenyaozong528** [AD-feiben/toutiao#2]
报错返回：b'{\n  "err_no": 1, \n  "message": "\\u8bf7\\u5b8c\\u6210\\u5b9e\\u540d\\u8ba4\\u8bc1\\u540e\\u91cd\\u8bd5\\u3002", \n  "code": 1\n}'

我看我账号是有认证过的。

**Comment by AD-feiben** [comment]
> 报错返回：b'{\n "err_no": 1, \n "message": "\u8bf7\u5b8c\u6210\u5b9e\u540d\u8ba4\u8bc1\u540e\u91cd\u8bd5\u3002", \n "code": 1\n}'
> 
> 我看我账号是有认证过的。


更新一下 Cookies，或者可以使用浏览器插件版本 https://github.com/AD-feiben/plugin-toutiao
